// <auto-generated />
using System;
using Lemon.Template.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lemon.Template.EntityFrameworkCore.DbMigrations.Migrations
{
    [DbContext(typeof(EfDbMigrationsContext))]
    partial class EfDbMigrationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lemon.Template.Domain.Account.Role.PermissionData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Adder")
                        .HasColumnType("bigint");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PermissionData", (string)null);
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Role.RoleData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Adder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("boolean");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleData", (string)null);
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Role.RolePermissionData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Adder")
                        .HasColumnType("bigint");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionData", (string)null);
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Users.UserData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Adder")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AllowEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AllowStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ChangPasswordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstVisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeadIcon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastVisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LogonCount")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MultiUserLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<DateTime>("PreviousVisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<bool>("UserOnline")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("UserData", (string)null);
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Users.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Adder")
                        .HasColumnType("bigint");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Role.RolePermissionData", b =>
                {
                    b.HasOne("Lemon.Template.Domain.Account.Role.RoleData", null)
                        .WithMany("RolePermissionDatas")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Users.UserRole", b =>
                {
                    b.HasOne("Lemon.Template.Domain.Account.Role.RoleData", "RoleData")
                        .WithOne()
                        .HasForeignKey("Lemon.Template.Domain.Account.Users.UserRole", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lemon.Template.Domain.Account.Users.UserData", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleData");
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Role.RoleData", b =>
                {
                    b.Navigation("RolePermissionDatas");
                });

            modelBuilder.Entity("Lemon.Template.Domain.Account.Users.UserData", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
